### ISSUE TITLE
critical (CRAN-blocking) issue

### ISSUE THREAD

**Issue by dankelley** [dankelley/ocedata#12]
Below is an email I just got.  I have not looked into this yet.

>This concerns packages
>
>DDPNA GCD GPoM Guerry HydroCode NMF NatureSounds RgoogleMaps
>SpatialAcc TSP ade4 bamlss belg clustree datos dnet dsm gibble
>glcm hypergate lctools link2GI nutshell.audioscrobbler ocedata palr
>primerTree ragt2ridges rangemodelR rdwd serrsBayes smoothr spBayes
>spData spaMM spatstat.data streamDepletr structSSI survivALL wpp2017 >wpp2019
>
>See the logs (and README.txt) at
>https://www.stats.ox.ac.uk/pub/bdr/noSuggests/ .
>
>At least one of the datasets cannot be loaded without a package declared
>in Suggests: -- typically this is because it loads a namespace defining
>S4 classes, and such imports should be declared in Imports or (as Matrix
>does) use a .R wrapper.  For example if I do
>
>data('Sample_ID_data', package = 'DDPNA')
>str(Sample_ID_data)
>
>namespaces
>
>BiocGenerics Biostrings IRanges S4Vectors XVector crayon zlibbioc
>
>get loaded, pulled in by Biostrings so the latter has to be available.
>
>Please correct ASAP and before Feb 20 to safely retain the package on >CRAN.

**Comment by dankelley** [comment]
The wrapper idea used by Matrix is at https://r-forge.r-project.org/scm/viewvc.php/pkg/Matrix/data/USCounties.R?view=markup&root=matrix I think.

**Comment by dankelley** [comment]
Below is a checklist of datasets.  I will look at each of them to see if they are 'oce' objects.  If they are, I'll click the box beside them.
* [ ] `RRprofile.rda`
* [ ] `beaufort.rda`
* [ ] `buoy.rda`
* [ ] `coastlineWorldFine.rda`
* [ ] `coastlineWorldMedium.rda`
* [ ] `conveyor.rda`
* [ ] `drag.rda`
* [ ] `endeavour.rda`
* [ ] `geosecs235.rda`
* [ ] `giss.rda`
* [ ] `gs.rda`
* [ ] `levitus.rda`
* [ ] `munk.rda`
* [ ] `nao.rda`
* [ ] `oceans.rda`
* [ ] `papa.rda`
* [ ] `redfieldNC.rda`
* [ ] `redfieldNP.rda`
* [ ] `redfieldPlankton.rda`
* [ ] `riley.rda`
* [ ] `schmitt.rda`
* [ ] `secchi.rda`
* [ ] `soi.rda`
* [ ] `topo2.rda`
* [ ] `turbulence.rda`
* [ ] `wilson.rda`

**Comment by dankelley** [comment]
OK, so I have 3 things to worry about
* `coastlineWorldFine.rda`
* `coastlineWorldMedium.rda`
* `geosecs235.rda`

**Comment by dankelley** [comment]
With a wrapper, this is what we'd have to reconstruct

```R
> str(coastlineWorldFine)
Formal class 'coastline' [package "oce"] with 3 slots
  ..@ metadata     :List of 4
  .. ..$ units   : list()
  .. ..$ flags   : list()
  .. ..$ filename: chr "/Users/kelley/src/ocedata/create_data/coastline/ne_10m_admin_0_countries.shp"
  .. ..$ fillable: logi TRUE
  ..@ data         :List of 2
  .. ..$ longitude: num [1:552670] NA -70 -69.9 -69.9 -69.9 ...
  .. ..$ latitude : num [1:552670] NA 12.6 12.5 12.5 12.5 ...
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:2], format: "2016-05-12 15:03:35.326" "2016-05-12 15:03:50.497"
  .. ..$ value: chr [1:2] "create 'coastline' object" "read.oce(file = \"ne_10m_admin_0_countries.shp\")"
```

---

```R
> str(coastlineWorldMedium)
Formal class 'coastline' [package "oce"] with 3 slots
  ..@ metadata     :List of 4
  .. ..$ units   : list()
  .. ..$ flags   : list()
  .. ..$ filename: chr "/Users/kelley/src/ocedata/create_data/coastline/ne_50m_admin_0_countries.shp"
  .. ..$ fillable: logi TRUE
  ..@ data         :List of 2
  .. ..$ longitude: num [1:100954] NA -69.9 -69.9 -69.9 -70 ...
  .. ..$ latitude : num [1:100954] NA 12.5 12.4 12.4 12.5 ...
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:2], format: "2016-05-12 15:03:56.628" "2016-05-12 15:03:57.717"
  .. ..$ value: chr [1:2] "create 'coastline' object" "read.oce(file = \"ne_50m_admin_0_countries.shp\")"
```

---

```R
> str(geosecs235)
Formal class 'ctd' [package "oce"] with 3 slots
  ..@ metadata     :List of 21
  .. ..$ units            :List of 22
  .. .. ..$ temperature    :List of 2
  .. .. .. ..$ unit :  expression(degree * C)
  .. .. .. ..$ scale: chr "ITS-90"
  .. .. ..$ salinity       :List of 2
  .. .. .. ..$ unit :  expression()
  .. .. .. ..$ scale: chr "PSS-78"
  .. .. ..$ conductivity   :List of 2
  .. .. .. ..$ unit :  expression()
  .. .. .. ..$ scale: chr ""
  .. .. ..$ pressure       :List of 2
  .. .. .. ..$ unit :  expression(dbar)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ depth          :List of 2
  .. .. .. ..$ unit :  expression(m)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ AOU            :List of 2
  .. .. .. ..$      :  expression(unit = mu * mol/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ bottle         :List of 2
  .. .. .. ..$ unit :  expression()
  .. .. .. ..$ scale: chr ""
  .. .. ..$ delta13C       :List of 2
  .. .. .. ..$ unit :  expression(per * mil)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ delta14C       :List of 2
  .. .. .. ..$ unit :  expression(per * mil)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ nitrite        :List of 2
  .. .. .. ..$ unit :  expression(mu * mol/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ nitrate        :List of 2
  .. .. .. ..$ unit :  expression(mu * mol/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ oxygen         :List of 2
  .. .. .. ..$ unit :  expression(mu * mol/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ pCO2           :List of 2
  .. .. .. ..$ unit :  expression(mu * atm)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ pCO2temperature:List of 2
  .. .. .. ..$ unit :  expression(degree * C)
  .. .. .. ..$ scale: chr "ITS-90"
  .. .. ..$ sigma0         :List of 2
  .. .. .. ..$ unit :  expression(kg/m^3)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ sigma2         :List of 2
  .. .. .. ..$ unit :  expression(kg/m^3)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ sigma4         :List of 2
  .. .. .. ..$ unit :  expression(kg/m^3)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ silicate       :List of 2
  .. .. .. ..$ unit :  expression(mu * mol/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ totalAlkalinity:List of 2
  .. .. .. ..$ unit :  expression(mu * equiv/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ theta          :List of 2
  .. .. .. ..$ unit :  expression(degree * C)
  .. .. .. ..$ scale: chr "ITS-90"
  .. .. ..$ totalCO2       :List of 2
  .. .. .. ..$ unit :  expression(mu * mol/kg)
  .. .. .. ..$ scale: chr ""
  .. .. ..$ tritium        :List of 2
  .. .. .. ..$ unit :  expression(TU)
  .. .. .. ..$ scale: chr ""
  .. ..$ flags            : list()
  .. ..$ pressureType     : chr "sea"
  .. ..$ deploymentType   : chr "profile"
  .. ..$ waterDepth       : logi NA
  .. ..$ names            : chr [1:22] "scan" "salinity" "temperature" "pressure" ...
  .. ..$ labels           : chr [1:22] "Scan" "Salinity" "Temperature" "Pressure" ...
  .. ..$ filename         : chr "geosecs235.cdf"
  .. ..$ ship             : chr ""
  .. ..$ scientist        : chr ""
  .. ..$ institute        : chr ""
  .. ..$ address          : chr ""
  .. ..$ cruise           : chr ""
  .. ..$ station          : num 235
  .. ..$ type             : chr ""
  .. ..$ model            : chr ""
  .. ..$ serialNumber     : chr ""
  .. ..$ src              : chr ""
  .. ..$ longitude        : num -161
  .. ..$ latitude         : num 16.8
  .. ..$ dataNamesOriginal: chr [1:22] "" "SAL" "TEMP" "PRESS" ...
  ..@ data         :List of 22
  .. ..$ scan           : int [1:120] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ salinity       : num [1:120] 34.4 34.3 34.3 34.3 34.4 ...
  .. ..$ temperature    : num [1:120] 25.7 25.8 25.8 25.8 25.7 ...
  .. ..$ pressure       : num [1:120] 5 10.1 17 33 40.3 ...
  .. ..$ AOU            : num [1:120] NA NA -2.5 -2.5 NA ...
  .. ..$ bottle         : num [1:120] 139 135 602 603 136 604 137 605 606 138 ...
  .. ..$ delta13C       : num [1:120] NA NA NA 0.8 NA ...
  .. ..$ delta14C       : num [1:120] NA 145 NA NA 149 ...
  .. ..$ depth          : num [1:120] 5 10 17 33 40 63 70 93 128 130 ...
  .. ..$ nitrite        : num [1:120] NA NA 0 0 NA ...
  .. ..$ nitrate        : num [1:120] NA NA 0 0 NA 0 NA 0 0 NA ...
  .. ..$ oxygen         : num [1:120] NA NA 207 207 NA 208 NA 211 213 NA ...
  .. ..$ pCO2           : num [1:120] NA NA NA NA NA NA NA NA NA NA ...
  .. ..$ pCO2temperature: num [1:120] NA NA 20 20 NA 20 NA 20 20 NA ...
  .. ..$ sigma0         : num [1:120] 22.7 22.6 22.5 22.5 22.7 ...
  .. ..$ sigma2         : num [1:120] 31 30.9 30.8 30.8 31 ...
  .. ..$ sigma4         : num [1:120] 38.9 38.8 38.8 38.8 38.9 ...
  .. ..$ silicate       : num [1:120] NA NA 2.2 2.2 NA ...
  .. ..$ totalAlkalinity: num [1:120] NA NA NA 2251 NA ...
  .. ..$ theta          : num [1:120] 25.7 25.8 25.8 25.8 25.7 ...
  .. ..$ totalCO2       : num [1:120] NA NA NA 1887 NA ...
  .. ..$ tritium        : num [1:120] NA 4.7 4.4 4.6 4.8 ...
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:1], format: "2016-05-12 19:51:01.764"
  .. ..$ value: chr "create 'ctd' object"
```

**Comment by dankelley** [comment]
I am testing the `Matrix` scheme in https://github.com/dankelley/ocedata2 ; see the issue tracker for that new repo, for details.

**Comment by dankelley** [comment]
I have https://github.com/dankelley/ocedata2 working now.  It does
```
R CMD build ocedata2
R CMD install ocedata2_0.1.6.tar.gz
R CMD check --as-cran ocedata2_0.1.6.tar.gz
```
properly.  It also works on the following test codes. From this, I conclude that I understand the wrapping scheme.  I will look into doing this with `ocedata` tomorrow.

**t1.R**

```R
library(ocedata2)
data("geosecs2352")
str(geosecs2352,2)
library(oce)
plotProfile(geosecs2352, xtype="salinity")
```

**t2.R**

```R
library(oce)
data("geosecs2352", package="ocedata2")
str(geosecs2352,2)
plotProfile(geosecs2352, xtype="salinity")
```

**Comment by dankelley** [comment]
commit 0c33657d79aa127a34194bfcf2717922747c817e
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Jan 24 08:09:30 2020 -0400

    geosecs235 is an R wrapper to avoid oce dependence

**Comment by dankelley** [comment]
commit fc5d9d4ffb5eeb6b501d5f140c48f7519eb17062
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Jan 24 08:37:42 2020 -0400

    coastline*: R wrappers to avoid oce dependence

**Comment by dankelley** [comment]
This passes all the tests that were required for the last CRAN submission.  There are likely more tests that I'll need to do when I try to submit, but in the meantime my plan is to build up oce again, and use it for a while to ensure that the new ocedata won't break oce.

Perhaps @richardsc and I can take a few moments in a f2f next week, to see if he can think of any reason why I shouldn't update ocedata on CRAN.  (I prefer not to wait, because the code changes are "in my head" now, which they won't be if we wait 3 weeks and try in the final few days of the deadlines.  Also if experience is any guide, there may be new wrinkles when I submit., and it's a bad idea to try to fix wrinkles when there is a clock ticking towards a deadline.)

**Comment by dankelley** [comment]
This check is now being one with `as-cran` and shows up in the Fedora builds at the cran check site.  This is nice because it tells us which datasets are a problem.  (I know that already for `ocedata`, and have fixed the problem, but still, this is a very helpful thing.)

https://cran.r-project.org/web/checks/check_results_ocedata.html

**Comment by richardsc** [comment]
Happy to chat, but I agree that updating ocedata sooner rather than later Ian a good idea.

**Comment by dankelley** [comment]
I've submitted to CRAN using `devtools::release(check=FALSE)`.  The use of `check=FALSE` is necessary because otherwise `release()` disobeys my `.Rproj` file and tries to overwrite some files. We cannot let it do that, because we are using a wrapper for some `data()` entries.

When/if it gets accepted, I will tag remove the file `CRAN-RELEASE` and tag the commit, following the instructions from `release()`.  Likely this will take 1-3 days, if we have clear sailing, but I'm glad I am submitting with 3 weeks before the deadline, just in case new problems arise.  (One never knows exactly how things will work on the official CRAN build machines.)

I will leave this issue open until the package appears on every last CRAN machine.  That might take a week or more, in the best case scenario.


commit f87323ad9486d156f8a256df6580246a82b8de10
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue Jan 28 08:53:14 2020 -0400

    submitted to cran

**Comment by dankelley** [comment]
The second stage of the upload (confirmation that I submitted the update, and that I followed the rules) is now complete. So now, we wait.  I think the system will need to check that `oce` (which suggests this) works with both the old an new version, and that check takes 1/2 hour for each test, so likely I'll know whether there is a bad failure by tommorow, depending on the size of the incoming cue for the CRAN engines.

**Comment by dankelley** [comment]
I guess the system trusts the pre-checks, because it just made it from ftp://cran.r-project.org/incoming/pretest/ to ftp://cran.r-project.org/incoming/publish/

**Comment by dankelley** [comment]
I'm making a checklist.  I'll monitor this from time to time.
* [ ] r-devel-linux-x86_64-debian-clang
* [ ] r-devel-linux-x86_64-debian-gcc 
* [ ] r-devel-linux-x86_64-fedora-clang 
* [ ] r-devel-linux-x86_64-fedora-gcc 
* [ ] r-devel-windows-ix86+x86_64 
* [ ] r-devel-windows-ix86+x86_64-gcc8 
* [ ] r-patched-linux-x86_64 
* [ ] r-patched-solaris-x86 
* [ ] r-release-linux-x86_64 
* [ ] r-release-windows-ix86+x86_64 
* [ ] r-release-osx-x86_64 
* [ ] r-oldrel-windows-ix86+x86_64 
* [ ] r-oldrel-osx-x86_64

**Comment by dankelley** [comment]
Hm.  I think (see https://github.com/dankelley/oce/issues/1648) that there is a problem with the three datasets that are handled with R files, namely
* [ ] `coastlineWorldFine.R`
* [ ] `coastlineWorldMedium.R`
* [ ] `geosecs235.R`

**Comment by dankelley** [comment]
Yes, my test indicate that the problem is in `ocedata`.  I think that means I'll be updating it in a few days ... but if @richardsc is at Dal tomorrow, we could also chat on this topic.

**Comment by dankelley** [comment]
commit e0b25966f2e8c95cd2c856012fe724883c83c7a5
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue Feb 4 12:24:39 2020 -0400

    specialized classes for coastline* and geosecs235

**Comment by dankelley** [comment]
commit 3704f7b8b80e5bba9f3601af635eee03918326a4
Author: dankelley <kelley.dan@gmail.com>
Date:   Wed Feb 5 07:30:04 2020 -0400

    use class tools (not ad-hoc changes) for subclasses

**Comment by dankelley** [comment]
Oh, I forgot to close this.  Things are clean now (see https://cran.r-project.org/web/checks/check_results_ocedata.html) that 0.1.6 has been accepted to CRAN
