### ISSUE TITLE
broken coastlineWorldFine

### ISSUE THREAD

**Issue by dankelley** [dankelley/ocedata#14]
I'm really confused, because I thought I had fixed this in the ocedata that is on CRAN right now, updated 3 months ago.  However, it seems not.  And I don't even see a bug report on this (although I've not checked that carefully yet), which is surprising because I remember seeing this problem and fixing it.

I view this as a critical bug because this coastline dataset is one of the main reasons for the existence of `ocedata`.

The bug is that the following code makes the plot as shown -- it is just plotting everything (with the CRAN version).  However, the "develop" branch works fine, I think.  I'll look into this some more, e.g. checking with the CRAN version of oce
```R
library(oce)
data(coastlineWorldFine, package="ocedata")
Belon <- -64.7505 # Longitude of Bermuda
Belat <- 32.3078 # Latitude of Bermuda
png("dan.png")
plot(coastlineWorldFine, clongitude=Belon, clatitude=Belat, span=200, col="tan")
dev.off()
```
![dan](https://user-images.githubusercontent.com/99469/79468389-3e683600-7fd5-11ea-9c21-38145026107d.png)

**Comment by richardsc** [comment]
Yes, I'm confused too because I thought we had this fixed ... let me dig around

**Comment by richardsc** [comment]
Here's the other issue where we dealt with this (in oce):

https://github.com/dankelley/oce/issues/1648

**Comment by richardsc** [comment]
What is the status on this? I thought we had it fixed, but I encountered it again today and was able to solve it by updating to the `ocedata` develop version (0.1.7). The CRAN version is at 0.1.6.

Do we need to update `ocedata` on CRAN?

**Comment by dankelley** [comment]
Maybe we do need an update.  Let me do a 2X2 test (cran/GH oce and cran/GH ocedata) to check that updating ocedata will not harm users of cran oce or GH oce.  I will edit this comment in-place so we have one single comment that tells the whole story. We know the answer to some of these, but still want to check carefully on the test code given below, to be sure, because if we release to CRAN and it's bad, we will likely be stuck for a long time with it.
* [ ] GH ocedata and GH oce: **(status?)**
* [ ] GH ocedata and CRAN oce: **(status?)**
* [ ] CRAN ocedata and GH oce: **(status?)**
* [ ] CRAN ocedata and CRAN oce: **(status?)**

Test code (status=OK if this shows as expected, BAD if shows whole world as in https://github.com/dankelley/ocedata/issues/14#issue-601107055
```R
# case4.R
remove.packages("oce")
remove.packages("ocedata")
install.packages("oce") # CRAN
install.packages("ocedata") # for CRAN test
library(oce)
data(coastlineWorldFine, package="ocedata")
Belon <- -64.7505 # Longitude of Bermuda
Belat <- 32.3078 # Latitude of Bermuda
png("case4.png")
plot(coastlineWorldFine, clongitude=Belon, clatitude=Belat, span=200, col="tan")
dev.off()
```

**Comment by dankelley** [comment]
@richardsc when you use ocedata from GH, are you using the 'master' branch or the 'develop' one?

**Comment by dankelley** [comment]
I conclude from the tests in https://github.com/dankelley/ocedata/issues/14#issuecomment-639373526 that updating the CRAN ocedata using the GH "master" branch (which is now in-synch with "develop") will fix the problem, whether the user has CRAN oce or GH oce.

I will therefore start further steps towards submission.  There are a lot of them, so my target submission time will be sometime on the weekend.  This gives @richardsc a bit of time to object, if necessary.

**Comment by dankelley** [comment]
This wIll hold a checklist of steps.  I will edit this comment in-place, adding new steps as needed.
* [ ] ensure that "develop" and "master" are identical
* [ ] update `NEWS` to `NEWS.md` (and use the format that pkgdown wants)
* [ ] set up for pkgdown building of webpage (involves creating `.pkgdown.yml` and adding it to `.Rbuildignore`)
* [ ] local (macos) build to check for NOTEs, WARNINGs, or ERRORs
* [ ] winbuilder (windows) check

**Comment by richardsc** [comment]
I see you've blown past me this morning, but I was using GH oce (develop) and GH ocedata (develop). I think a submission is a good idea. Let me know if you need anything else!

**Comment by dankelley** [comment]
I have submitted to CRAN, and will *update this comment in-place* (to avoid having to scroll through screens of comments), as the submission goes through the steps of checking.

**Comment by dankelley** [comment]
The new version is now on all CRAN platforms, so I'm closing this.  Thanks, team!
