### ISSUE TITLE
update levitus (use 2013 instead of 2009)

### ISSUE THREAD

**Issue by dankelley** [dankelley/ocedata#2]
Will need to slice/dice the matrices (method tested in OAR sandbox/levitus)

**Comment by dankelley** [comment]
Also, since Levitus retired in 2013 and the official name has been WOA for a long time ... I guess the dataset needs to be renamed ``woa``.

**Comment by richardsc** [comment]
I don't know, I like name levitus and I think the other WOA authors might agree. Check out the dedication page in the [2013 documentation](http://data.nodc.noaa.gov/woa/WOA13/DOC/woa13_vol1.pdf):

> The WOD and WOA series are used so frequently that they have become known generically as the “Levitus Climatology”. These databases and products enable systematic studies of ocean variability in its climatological context that were not previously possible. His foresight in creating WOD and WOA has been demonstrated by their widespread use over the years.

Is it possible to use aliases for data sets the way you can do for functions? Then it could be both woa and levitus. 

Also, what do you think about including the other variables (oxygen and nutrients) available as part of woa?

**Comment by dankelley** [comment]
Thanks!  I've got a long reply so I'll use subheadings.  (Again, I wish GH had proper issue threading. Then you could post two comments and each could get a reply, with your replies to that, etc. Much easier to follow.)

**NAME**  There can be a documentation alias, for sure.  There could also (I suppose) be an "on-load" function that does ``levitus<-woa`` but that would increases memory usage. (The memory is not a big deal for the user and this would not be counted in the package size.)

I still lean towards ``woa`` because that's what the agency has called the dataset for as long as I remember.

**OTHER DATA** I lean towards limiting to the present SST and SSS.  Adding the other depths increases the memory by a factor of something like 170 (they increased the number of levels in 2013), putting the package data size at 30Mb, clearly over the CRAN limit.  Adding oxygen and 4 nutrients at z=0 would also cost a lot of space and I don't think there would be much signal (guessing oxygen will be saturated and the others will be low owing to primary production). There are other products that I'd prefer to oxygen and nutrients, e.g. mixed-layer depth.  (They used to have that ... I've not checked for this version of the atlas.)

Luckily, however, I don't think there is much need to provide all these things because it's just 4 lines to drink the netcdf data directly. This will be just as fast as loading an rda file (I think), and it has the advantage of connecting the user more directly with the data (e.g. they will need to download the data, and presumably they will also download the docs to learn about how the data were gridded etc).

The idea of providing SSS and SST is just that they can be helpful for tons of general graphs. I see them as like topography ... in a talk, an SST plot is a nice background for a study-site graph ("we are sampling in the subpolar gyre") or a discussion of wind-driven gyres ("notice how the warm water detaches from the coast near Hatteras") etc. This is my reason for not deleting them. However, I do have in mind (if another important dataset comes up for inclusions) decimating them to 2deg, which would reduce the file size by 4X, freeing up 150Kb for another file...as you can see, I always have in mind the issue of CRAN rejection.

**Summary.** Sorry this is so long. I am afraid I still think ``woa`` is the proper name. And I think expanding the docs will (a) let people learn by typing ``?levitus`` and (b) let people see how easy it is to drink the ncdf data themselves.

**Comment by dankelley** [comment]
I decided that I didn't care all that much about the name. Since you voted to keep ``levitus``, I've done that. There is now a doc alias for ``woa``, and the docs explain why the dataset is called ``levitus``. I also include the code required to create the dataset, with a hint that similar can be used for other work. And the updated URLs are listed too.

Any further thoughts, @richardsc?

**Comment by richardsc** [comment]
That sounds great! Nice to hear that I can be so persuasive! :) This is your issue to close if you're happy.

**Comment by dankelley** [comment]
Thanks! Closing.
